Vagrant.configure("2") do |config|
  config.vm.guest = :netbsd
  config.ssh.shell = "sh"
  config.ssh.sudo_command = "su -m root -c '%c'"
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
