Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/haiku-i386"

    config.vm.provision "file", source: "flag.txt", destination: "/boot/home/flag.txt"
    config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end
