#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

echo 'vagrant: :path=/usr/bin /bin /usr/sbin /sbin /usr/X11R7/bin /usr/X11R6/bin /usr/pkg/bin /usr/pkg/sbin /usr/local/bin:' >>/etc/login.conf &&
    cap_mkdb /etc/login.conf &&
    useradd -m -g staff -G wheel -L vagrant vagrant &&
    PASSWORD_HASHED="$(echo 'vagrant' | pwhash)" &&
    usermod -p "$PASSWORD_HASHED" vagrant &&
    sed -i \
        -e 's/^#UseDNS no/UseDNS no/' \
        -e 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' \
        -e 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/' \
        /etc/ssh/sshd_config &&
    printf "dhcpcd=YES\nntpdate=YES\nsshd=YES\n" >>/etc/rc.conf &&
    sh /etc/rc.d/sshd onestart
