#!/bin/sh
unset IFS
set -euf

mkdir -p /home/vagrant/.ssh &&
    ftp -o /home/vagrant/.ssh/authorized_keys https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub &&
    chmod 0700 /home/vagrant/.ssh &&
    chmod 0600 /home/vagrant/.ssh/authorized_keys &&
    sudo env PKG_PATH=https://www.mirbsd.org/MirOS/v10/Pkgs/i386 /usr/mpkg/sbin/pkg_add rsync-3.0.2-0 &&
    sudo mkdir -p /vagrant &&
    sudo chown vagrant:vagrant /vagrant &&
    sudo rm -rf /tmp/* &&
    sudo su -c "dd if=/dev/zero of=/whitespace bs=1048576 || echo 'Zeroed disk' && rm -f /whitespace && sync" &&
    sudo shutdown -h -p now
