Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/os-2"

    config.vm.provision "file", source: "flag.txt", destination: "C:\\vagrant\\flag.txt"
    config.vm.provision "shell", path: "bootstrap.bat"
end
