Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/debian-ppc64el"

    config.vm.provision "file", source: "flag.txt", destination: "/home/vagrant/flag.txt"
    config.vm.provision "shell", path: "bootstrap.sh"
end
