Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/void"

  config.vm.provision "file", source: "flag.txt", destination: "/home/vagrant/flag.txt"
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end
