Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/haiku"

  config.vm.provision "file", source: "flag.txt", destination: "/boot/vagrant/flag.txt"
  config.vm.provision "shell", path: "bootstrap.sh"
end
