Vagrant.configure("2") do |config|
  config.vm.guest = :solaris11
  config.solaris.suexec_cmd = ""
  config.ssh.sudo_command = "print \".\nvagrant\n\" | /usr/lib/embedded_su root -c '%c'"
  config.vm.synced_folder ".", "/opt/vagrant", type: "rsync", rsync__chown: false
end
