Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/windows-i386"

  config.vm.provision "file", source: "flag.txt", destination: "C:\\Users\\vagrant\\flag.txt"
  config.vm.provision "shell", path: "bootstrap.ps1"
end
