Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/9front"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "file", source: "flag.txt", destination: "/usr/vagrant/flag.txt"
  config.vm.provision "shell", path: "bootstrap.sh"
end
